### ISSUE TITLE
Windows binary icon and description still refer to Godot Engine

### ISSUE THREAD

**Issue by andygeorge** [AriaMoradi/Catapult#1]
Seen here are the properties of `catapult-win-x64-24.03a.exe`:

 ![image](https://github.com/AriaMoradi/Catapult/assets/10601857/df02b7cc-24bc-445b-96ca-5bed56cf8c51)

Haven't tried out the binary in Linux quite yet.

**Comment by AriaMoradi** [comment]
duplicate of #2
