### ISSUE TITLE
Font folder not working as intended.

### ISSUE THREAD

**Issue by CaseMonster** [AriaMoradi/Catapult#11]
When launching the game, it doesn't appear to find any fonts located in .\dda\userdata\font.
It will find them when placing them manually in .\dda\game0\data\font.

The config file at .\dda\userdata\config\fonts.json is read properly.

The launcher also throws an error upon switching to the fonts tab.

![image](https://github.com/AriaMoradi/Catapult/assets/1514890/c04de037-84f1-4d28-b9fb-0b37071cd185)

My fonts.json looks like this:

{
  "typeface": [
    "data/font/CascadiaCode.ttf",
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "map_typeface": [
    "data/font/CascadiaCode.ttf",
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ],
  "overmap_typeface": [
    "data/font/CascadiaCode.ttf",
    "data/font/Terminus.ttf",
    "data/font/unifont.ttf"
  ]
}

**Comment by AriaMoradi** [comment]
Fixed in 24.04a
